# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- main

resources:
- repo: self

variables:
- group: ImagePush

steps:
# Step 1: Checkout the code
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use the appropriate .NET version

# Step 2: Restore dependencies
- script: |
    dotnet restore
  workingDirectory: HelloWorld
  displayName: 'Restore dependencies'

# Step 3: Build the .NET application
- script: |
    dotnet build --configuration Release
  displayName: 'Build application'
  workingDirectory: HelloWorld

# Step 4: Publish the build output
- script: |
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
  workingDirectory: HelloWorld
  displayName: 'Publish application'

# Step 5: Get the next version tag
- script: |
    docker login -u $(dockerHubUsername) -p $(dockerHubPassword)
    current_version=$(docker images $(dockerHubImageName) --format "{{.Tag}}" | grep -E "^v[0-9]+" | sort -r | head -n 1 | sed 's/v//')
    
    if [ -z "$current_version" ]; then
        next_version=1
    else
        next_version=$((current_version + 1))
    fi

    echo "##vso[task.setvariable variable=nextVersion;]v$next_version"
    echo "Next version: v$next_version"
  displayName: 'Determine next version tag'


# Step 6: Build Docker image with next version
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    repository: '$(dockerHubImageName)'
    Dockerfile: 'HelloWorld/Dockerfile'  # Ensure you have a Dockerfile in the repo root
    tags: |
      $(nextVersion)

# Step 7: Push Docker image with next version
- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: 'push'
    repository: '$(dockerHubImageName)'
    tags: |
      $(nextVersion)