# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- main

resources:
- repo: self

variables:
  - group: ImagePush
  - name: tag
    value: '$(Build.BuildId)'

steps:
# Step 1: Checkout the code
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use the appropriate .NET version

# Step 2: Restore dependencies
- script: |
    dotnet restore
  workingDirectory: HelloWorld
  displayName: 'Restore dependencies'

# Step 3: Build the .NET application
- script: |
    dotnet build --configuration Release
  displayName: 'Build application'
  workingDirectory: HelloWorld

# Step 4: Publish the build output
- script: |
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
  workingDirectory: HelloWorld
  displayName: 'Publish application'

# Step 5: Build Docker image with Build.BuildId as tag
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    repository: '$(dockerHubImageName)'
    Dockerfile: 'HelloWorld/Dockerfile'
    tags: |
      $(tag)  

# Step 6: Push Docker image with Build.BuildId as tag
- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: 'push'
    repository: '$(dockerHubImageName)'
    tags: |
      $(tag)  